export PATH=$HOME/.bin:$HOME/.local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"

# ZSH_THEME=""

fetcho
eval "$(starship init zsh)"

zstyle ':omz:update' mode reminder
zstyle ':omz:update' frequency 5

HIST_STAMPS="dd/mm/yyyy"

source ~/.dotfiles/theming/catppuccin-zsh-syntax-highlighting/catppuccin-zsh-syntax-highlighting.zsh
plugins=(git sudo archlinux zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

export EDITOR="/bin/nvim"

[ -f "$HOME/.aliasrc" ] && source "$HOME/.aliasrc"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
